In [1]:
class Claim:
    def __init__(self, *args):
        print(args)
        self.__subject = args[0]
        self.__predicate = args[1]
        self.__object = args[2]
    
    @property
    def predicate(self):
        return self.__predicate
    
    @predicate.setter
    def predicate(self,v):
        self.__predicate = v

In [2]:
params = ['obama', 'bornin', 'kenya']
claim = Claim(*params)

('obama', 'bornin', 'kenya')


In [3]:
a = 'abc'
b = 'abc'
print(a==b)

True


## Numpy 

In [9]:
import numpy as np
import numpy.linalg as la
from nltk.metrics import distance as sdis

In [10]:
claims = ['kenya', 'kenya', 'usa', 'indonesia', 'usa']
claim_set = list(set(claims))

In [11]:
print(claims)
print(claim_set)

['kenya', 'kenya', 'usa', 'indonesia', 'usa']
['kenya', 'usa', 'indonesia']


In [13]:
def impl(value1, value2):
    """
    implication function of (value1 -> value2)
    Truth Finder use impl(f1->f2) to measure how much fact f1 supports
    fact f2, where f1 and f2 is about the same entity.

    We assume now value1 and value2 are strings.
    """
    return np.exp(-sdis.edit_distance(value1,value2)) - 0

In [14]:
impl('kenya', 'kenya')

1.0

In [15]:
impl('kenya', 'usa')

0.018315638888734179

In [16]:
impl('usa', 'kenya')

0.018315638888734179

In [20]:
sigma_i = [2, 3, 4]


In [21]:
print(sigma_i)
print(claim_set)

[2, 3, 4]
['kenya', 'usa', 'indonesia']


In [37]:
implication_1 = [impl(c, 'kenya') for c in claim_set]
print(implication_1)

[1.0, 0.018315638888734179, 0.00091188196555451624]


In [38]:
implication_1 = np.array(implication_1)
sigma_i = np.array(sigma_i)
print(implication_1)
print(sigma_i)

[  1.00000000e+00   1.83156389e-02   9.11881966e-04]
[2 3 4]


In [39]:
implication_1 * sigma_i

array([ 2.        ,  0.05494692,  0.00364753])

array([ 2.        ,  0.05494692,  0.00364753])

In [36]:
1.83156389e-02 * 3

0.0549469167

In [42]:
implication_1[0]

1.0

## Numpy slicing

In [43]:
a = np.array([2,3,4,4])

In [44]:
mask = [True, True, False, True]
print(a[mask])

[2 3 4]


In [45]:
print(type(a[mask]))

<class 'numpy.ndarray'>


In [46]:
mask2 = [True, False, False, False]

In [55]:
entity_to_claims = [np.array([], dtype=int) for i in range(10)]

In [57]:
entity_to_claims[1].append(2)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [49]:
sum(a[mask2])

2

In [51]:
a[[0,2]]

array([2, 4])

In [59]:
a

array([2, 3, 4, 4])

In [60]:
b = 4

In [63]:
a == b

array([False, False,  True,  True], dtype=bool)

In [64]:
entity_to_claims = [np.array([]) for i in range(10)]

In [65]:
entity_to_claims

[array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64)]

In [78]:
confidence = np.array([2,3,3,4, 5])

In [79]:
np.argmax(confidence)

4

In [80]:
np.max(confidence)

5